### ISSUE TITLE
Continue scanning until back or cancel button is pressed

### ISSUE THREAD

**Issue by ProProjects11** [fttx/barcode-to-pc-app#10]
Hello, this app is pretty amazing (It's the best among all the ones I have tried)

It will be nice if by default the app continue scanning until back or a cancel button is pressed in the scan screen, instead of having to select continue in the "continue scanning?" dialog every single time. I scan around 20 barcodes per session and is very inefficient having to press continue every time.

Thanks for this great app.

**Comment by fttx** [comment]
Thanks for contacting! This was already on the todos pile.

Unfortunatelly it isn't possible do that inside the "scan screen" due to the way [barcode scanner plugin](https://github.com/phonegap/phonegap-plugin-barcodescanner) is made
A possible solution could be to put a timeout that automatically re-launches the scan screen if the user doesn't click back

https://github.com/fttx/barcode-to-pc-server/issues/7

**Comment by fttx** [comment]
[android-release.apk.zip](https://github.com/fttx/barcode-to-pc-app/files/774853/android-release.apk.zip)

**Comment by ProProjects11** [comment]
Hello, thank you very much, Continue mode is working pretty nice. :)

**Comment by ppc52776** [comment]
How to enable continue mode?

**Comment by fttx** [comment]
Install the apk above and enable Continue mode from the menu drawer (slide left). Btw i think that i will release an update within this week.

**Comment by ppc52776** [comment]
My phone doesn't have menu button, is there other way to open the menu ?

**Comment by fttx** [comment]
Yes, do a swipe gesture or tap on the menu icon on the left hand side.

**Comment by ppc52776** [comment]
I can't find menu icon?  how to swipe?
![5676570559398](https://cloud.githubusercontent.com/assets/882182/23131640/590e3c68-f750-11e6-8010-2b08dcd6d709.jpg)

**Comment by fttx** [comment]
Did you install the apk? https://github.com/fttx/barcode-to-pc-app/issues/10#issuecomment-279778407

**Comment by ppc52776** [comment]
yes, but the version shows 1.0.0 not 1.0.2 ?

**Comment by fttx** [comment]
You're running the older version (the one of the playstore). Don't look at the version name, i haven't updated it yet in the apk

**Comment by ppc52776** [comment]
I install the apk #10.

**Comment by fttx** [comment]
So you should see the menu icon:
![image](https://cloud.githubusercontent.com/assets/5663423/23137585/0b1381dc-f7a3-11e6-9a51-eda30fda1e01.png)

**Comment by ppc52776** [comment]
sorry, my fault, the menu botton appear now.

**Comment by ppc52776** [comment]
continue mode still go back and go in
