### ISSUE TITLE
Wrong EAN codes

### ISSUE THREAD

**Issue by niccoX** [fttx/barcode-to-pc-app#110]
Not very often but occasionally the wrong barcodes are scanned/saved. Using current Android app.

**Comment by fttx** [comment]
The current version tries to scan all barcode formats, with the next version you'll be able to select only the one that you use, so that it'll be faster and reliable.
See: https://github.com/fttx/barcode-to-pc-app/issues/76

**Comment by niccoX** [comment]
Ok, when is that release planned?

It makes errors on EAN codes all to often, sometimes the whole code is wrong, other times a part of the code, usually the end of the barcode.

I have to double check everytime I do a scan.
