### ISSUE TITLE
[FEAT] Use Abby free OCR SDK to include ability to scan product codes in full alphanum

### ISSUE THREAD

**Issue by huafu** [fttx/barcode-to-pc-app#114]
Your app is great, and in our case we're using it to check missing products in our tiny store, and/or to update ray labels which are missing either product code or barcode. When the barcode is missing, we need to switch to the Notes app or write the article code by hand somewhere.

Using [this free SDK](https://rtrsdk.com/) you could add a feature in your app which would allow it to also scan small piece of text such as article codes, or even the number of the barcode if the barcode is not readable.

I will understand if this get closed as a "won't fix", but it would really be a great addition to the app.

Thanks again for this wonderful app!

**Comment by fttx** [comment]
v3.0.0 will include a way to type a barcode.
Maybe in the next version.

https://ionicframework.com/docs/native/abbyy-real-time-recognition/
