### ISSUE TITLE
iOS app crashing in version 3.1.0.

### ISSUE THREAD

**Issue by fmgegypt** [fttx/barcode-to-pc-app#124]
App opens up fine. But as soon as you try to scan it crashes. Connection to pc works. Just the crashing upon firing up a scan.

**Comment by fttx** [comment]
Hi, thanks for the report, i didn't catch that, the update is already on its way.

Would you like to be added to the beta testers?

**Comment by fmgegypt** [comment]
Confirmed it's working again now after the update. Thank you. Not sure how we can be beta testers.
How would we install on ios unless it's published already.

**Comment by fttx** [comment]
You have to install the TestFlight app: https://itunes.apple.com/app/testflight/id899247664?mt=8
It allows you to get the updates before they're published and also to select the older versions of the app.

To gain the access to the beta testers group you have to open this link from the smartphone: https://testflight.apple.com/join/uClK7lDq

Let me know if it works
