### ISSUE TITLE
[3.1.0] On single mode new scannings got empty

### ISSUE THREAD

**Issue by hugho-ad** [fttx/barcode-to-pc-app#127]
V 3.1.0, server barcode-to-pc-server-3.1.0-x86_64

When scanning a new barcode on single mode, no barcode is scanned, just an empty one.

![image](https://user-images.githubusercontent.com/10233975/60478237-8fc25700-9c47-11e9-80b6-226ebe779b27.png)

**Comment by fttx** [comment]
Can you confirm that the version displayed in the app About page is actually 3.1.0?
And also the server version in the Info page?

Thanks

**Comment by hugho-ad** [comment]
sure, here you go
![image](https://user-images.githubusercontent.com/10233975/60488759-6a921080-9c68-11e9-891d-83b391492e51.png)


![image](https://user-images.githubusercontent.com/10233975/60488805-87c6df00-9c68-11e9-8a64-d1df1e2a4793.png)

**Comment by hugho-ad** [comment]
In order to continue scanning, I down degree the app version to 3.0.2, then I made my scanning, re-update the app, and re-sent the barcodes, that was the only way that I find that allows me to keep working with the app.

Regards!

**Comment by fttx** [comment]
I'm unable to reproduce this, but i think that it's related to the Output field of the server.
Can you provide your config file? Use this command to copy it to the desktop:
`cp /home/$USER/.config/barcode-to-pc-server/config.json /home/$USER/Desktop`

To fix it try remove and then add a component, and save the settings. Or just remove the config.json and start the server again

Thank you!

**Comment by hugho-ad** [comment]
you right!

It works now, thanks!

I'll close this issue
