### ISSUE TITLE
TypeScript Error , I can't start the app

### ISSUE THREAD

**Issue by BigDee123** [fttx/barcode-to-pc-app#131]
[TypeScriptError.txt](https://github.com/fttx/barcode-to-pc-app/files/3361535/TypeScriptError.txt)

**Comment by fttx** [comment]
Perhaps you're using a different typescript version, try to match the one in the https://github.com/fttx/barcode-to-pc-app/blob/master/package.json

**Comment by BigDee123** [comment]
it worked that you.
