### ISSUE TITLE
Deleting session in offline

### ISSUE THREAD

**Issue by MStcz** [fttx/barcode-to-pc-app#221]
In case you decide to use IOS app just in offline mode. It is not possible to delete scan session. It would be great to get an option to delete it even the app is in offline.

**Comment by stargladius** [comment]
That's not only IOS. Android too. And this function was present some time ago. I have used this app mostly offline. But have to switch to another when it was removed or disabled.

**Comment by fttx** [comment]
It was introduced to prevent inconsistency between app and server -> https://github.com/fttx/barcode-to-pc-app/commit/860fe343e643272931b5430bab261958c4e2cc69

It was a really old version > v3.0.0

Download app: https://github.com/fttx/barcode-to-pc-app/releases/download/v2.0.4/barcode-to-pc-app-v2.0.4.apk
Download server: https://github.com/fttx/barcode-to-pc-server/releases/download/v2.0.0/barcode-to-pc-server.v2.0.0.win.setup.exe

**Comment by fttx** [comment]
So basically you need to delete the scans that aren't received yet so that you can sync only the correct ones later?

In that case, I may enable it again but will work only if the scan session or (scan) hasn't been sent yet

**Comment by stargladius** [comment]
You are fully correct)). Yes, only for those that are not synced with server yet.

**Comment by fttx** [comment]
I've added the support to the new version. Can you please test it?

Server: https://ci.appveyor.com/api/buildjobs/c3tyas0amrd0nb1j/artifacts/dist%2Fdist%2Fbarcode-to-pc-server.offline-installer.zip (Extract everything and then execute the .exe)
App: [barcode-to-pc-app-v3.15.0-beta1.apk.zip](https://github.com/fttx/barcode-to-pc-app/files/6517015/barcode-to-pc-app-v3.15.0-beta1.apk.zip)

Also, can you make sure that there aren't inconsistencies between the app and the server?

Thank you 🙏

**Comment by fttx** [comment]
Sorry, you can ignore the previous message, I'm testing a few things, I will provide a new beta version later today

**Comment by fttx** [comment]
Oh, ok I'll send an .appimage file then

**Comment by fttx** [comment]
Windows: https://ci.appveyor.com/api/buildjobs/jsmxn99jfp2qml6s/artifacts/dist%2Fdist%2Fbarcode-to-pc-server.offline-installer.zip
Linux: https://www.dropbox.com/s/3lv4gjmddwi3ys6/barcode-to-pc-server.v3.14.0.linux.x86_64.AppImage.zip?dl=1

App (Android): [barcode-to-pc-app-v3.15.0-beta2.apk.zip](https://github.com/fttx/barcode-to-pc-app/files/6518600/barcode-to-pc-app-v3.15.0-beta2.apk.zip)

**Comment by stargladius** [comment]
Got it. Will try today. 
How is will be better to send you results? Here or direct e-mail?

**Comment by fttx** [comment]
Doesn't matter I check both 🤣

**Comment by stargladius** [comment]
For now I have done next tries. Sorry for my bad bad English.

   Play 1. Offline.
1. Have made some scans in offline mode.
2. Have deleted sessions without problems.

   Play 2. Scans offline, full sync later
1. Have made some scans in offline.
2. Have connected to server.
3. Have synced full sessions.
4. Cannot delete synced sessions in offline mode. With message that they are synced.


   Play 3. Scans offline. Partial sync of session.
1. Have made some scans in offline.
2. Have connected to server.
3. Have synced scans in session. They became green-marked
4. Gone to offline.
5. Have made some additional scans in that session. 
5. Have tried to delete session but cannot with message that some of results are already synced. With green mark.
6. But I can delete in session result with red mark, not synced.
7. Have connected to server.
8. Successfully deleted green-mark results in session. After that I have disabled the server (offline). 
   And successfully deleted whole sessions. Those sessions that was without any results
   and those that was with red mark only results.
9. But on server all synced sessions and results are still present.


   Play 3. Delete already synced on phone.
When I have deleted already synced scan results in session, on server they are still remain. Even If I re-sync session. As I understand sync is one direction only. But new one scan result was added to session on server.

   Play 4. Delete session on server.
I have deleted session on server. But it still remain in my smartphone. I cannot re-sync it. When i go to session and click re-sync it do some thing but no session on server appear. Then i go to smartphone and try to delete this session on smartphone. Despite on green-mark in results, it have been deleted without problems. Server was connected. On the same time there was no any sessions in server.

**Comment by fttx** [comment]
Yes, the sync option is one-direction only, and from what you said it is working as intended.

The reason why you see the empty scan sessions and also why it won't let you sync partials scan sessions is because when it is archived/restored the scans are sent in batch, and not one by one.

The issue arises when the output template contains a component such as RUN, CSV_LOOKUP, etc. that requires to be executed server-side, and thus batch mode can't be used, so I'm temporarily disabling the option to sync partial scan sessions.

If it isn't a big usability issue I'll leave it as it is.

**Comment by fttx** [comment]
Now it should work also offline. The only time when it's required to use the sync button is when there is the red (!) icon.

Windows: https://ci.appveyor.com/api/buildjobs/idf1pjn20pqov71y/artifacts/dist%2Fdist%2Fbarcode-to-pc-server.offline-installer.zip
Linux: https://www.dropbox.com/s/3lv4gjmddwi3ys6/barcode-to-pc-server.v3.14.0.linux.x86_64.AppImage.zip?dl=1
Android: [barcode-to-pc-app-v3.15.0-beta3.apk.zip](https://github.com/fttx/barcode-to-pc-app/files/6526181/barcode-to-pc-app-v3.15.0-beta3.apk.zip)

Note: it won't work with scan sessions created prior to this beta3 update

**Comment by stargladius** [comment]
Hello.
Have tested new version today.
Some thing gone wrong. In partial scans synced. I have successfully removed session with already synced results in offline.
Play 1. Re check partial sync scans in session.
1. Made some scans.
2. Connect to server.
3. Sync those scans. They became green-marked
4. Gone to offline. 
5. Made some additional. So in session there ware 4 green and 2 red.
6. Have deleted session without warnings(.

> Yes, the sync option is one-direction only, and from what you said it is working as intended.
> 
> The reason why you see the empty scan sessions and also why it won't let you sync partials scan sessions is because when it is archived/restored the scans are sent in batch, and not one by one.
> 
> The issue arises when the output template contains a component such as RUN, CSV_LOOKUP, etc. that requires to be executed server-side, and thus batch mode can't be used, so I'm temporarily disabling the option to sync partial scan sessions so that the user is forced to use the sync button which will send the scan one by one.
> 
> If it isn't a big usability issue I'll leave it as it is.

If batch mode sync is working as intended, so let it be).

**Comment by stargladius** [comment]
Please correct if I understand something wrong. Now you have made the ability to delete any session with already synced scans to server even if the server in not connected?

**Comment by fttx** [comment]
Correct. Once the app connects again it will send the archive/restore command so that you'll see the same sessions on the main screen of the server.

**Comment by stargladius** [comment]
Ah! Cool!

**Comment by stargladius** [comment]
I have checked. But cannot see it as I understand)). But with my English it could be just my misunderstanding.
I have made 3 sessions with some scans.

Play 1. Deleted on server.
1. Made sessions 1 and 2 in offline.
2. Connected to server and synced them with button in each one
3. Disconnected from server.
4. Deleted session "2" on server.
5. Reconnected to server and nothing happened. There are still session "1" and "2" on smartphone. But on server only session "1"

Play 2. Deleted on smartphone.
1. I have made additional session "3" and it synced to server.
2. Then I have gone offline and deleted it in smartphone. So now in smartphone i have only session "1" and "2" as it was after "Play 1". But on server there are sessions "1" and "3"
3. I have reconnected to server and again nothing happened.
4. I see in smartphone sessions "1" and "2". On server I see "1" and "3"

**Comment by fttx** [comment]
Play 1. Yes, that it's expected, the sync can happen only from the smartphone to the server
Play 2. I'm unable to reproduce step 3. It should delete the scan session from the server as well, leaving with this:

![image](https://user-images.githubusercontent.com/5663423/119344694-3ed30600-bc98-11eb-882d-6c9635931731.png)

![IMG_3BB2E34099C3-1](https://user-images.githubusercontent.com/5663423/119344781-57432080-bc98-11eb-90f6-e1827766b05d.jpeg)

**Comment by stargladius** [comment]
> Play 1. Yes, that it's expected, the sync can happen only from the smartphone to the server

Got it. Thanks.

> Play 2. I'm unable to reproduce step 3. It should delete the scan session from the server as well, leaving with this:

I will try it this evening with windows server version and let you know

**Comment by stargladius** [comment]
In Windows version of the server Play 2 work correct, as you describe. It sync on reconect and deletes already deleted on smartphone sessions.
