### ISSUE TITLE
How to properly refer to multiple barcode objects in single output format

### ISSUE THREAD

**Issue by jsormaz** [fttx/barcode-to-pc-app#225]
If I have multiple barcode objects as shown in the example:
![image](https://user-images.githubusercontent.com/29971327/107443084-bf149780-6afd-11eb-97a1-cbd277d2938d.png)
How do I refer to them individually? for example to compare if they are identical.

All docs always refer to them as "barcode". can I index them somehow?

**Comment by fttx** [comment]
Unfortunately, it's not possible, the _barcode_ variable gets overwritten every time a new barcode is acquired.

ref.
- https://github.com/fttx/barcode-to-pc-server/issues/197
- https://github.com/fttx/barcode-to-pc-server/blob/82c0a475feded45e657b55e40adf7bff1f4c80f7/electron/src/handlers/scans.handler.ts#L175

**Comment by jsormaz** [comment]
ok. I ended up accomplishing this by putting a "run" component between the scans which writes the first barcode to a temp file. A separate run component after the second barcode then has access to both barcodes

It's a workaround, but it works. Just not super robust.

**Comment by fttx** [comment]
Now you can use the `barcodes` variable to access the barcodes.
Example: `barcodes[0]`

https://github.com/fttx/barcode-to-pc-app/commit/78e99bfa273903173ce912d4213e54479eb377e3
