### ISSUE TITLE
Does this app (specially Windows based app) store the scan data only locally or also externally to any other server?

### ISSUE THREAD

**Issue by Prathameshhankare** [fttx/barcode-to-pc-app#250]
I want to know if the barcode data is stored only locally or it is also stored externally. It is a security concern for us if it stores the data externally somewhere.

I haven't found anything related to this and I am using the windows based server app and mobile app for the scan to store.

**Comment by fttx** [comment]
It's all stored locally, and by default it connects through the local network (LAN) as a matter of fact you can continue using the app even without an active Internet connection.

**Comment by Prathameshhankare** [comment]
Thank you @fttx for confirming, I really appreciate your quick response.
