### ISSUE TITLE
Issue with Swiss QR Code

### ISSUE THREAD

**Issue by gemaroup** [fttx/barcode-to-pc-app#290]
Hi,
While analyzing data scanned using swiss qr codes I noted that "return" spaces were added compared to original data. This creates an error while importing invoices in my swiss payments program (Paymaker). Can u hel
[SPC Barcode to PC.pdf](https://github.com/fttx/barcode-to-pc-app/files/9908801/SPC.Barcode.to.PC.pdf)
p? Thx a lot.

**Comment by fttx** [comment]
Try to enable the Clipboard Type method in the server settings, like this:
<img width="521" alt="Screenshot 2022-11-01 at 11 25 08" src="https://user-images.githubusercontent.com/5663423/199213075-938a3b7b-80ca-4425-b449-3dfddfd8ec42.png">
<img width="524" alt="Screenshot 2022-11-01 at 11 25 15" src="https://user-images.githubusercontent.com/5663423/199213098-d8f25cca-7f16-40ec-ba0e-6f1b55dd6cd0.png">

**Comment by fttx** [comment]
Yes, that option wasn't that useful, that's why I removed it 🙂
