### ISSUE TITLE
4.5 Image Component LineageOS 

### ISSUE THREAD

**Issue by gitschwarz** [fttx/barcode-to-pc-app#304]
I run the android app on Lineage OS 20.0
The new image component doesn't work.
On the server side  I have a simple template

image (with path) enter

I choose the template in the app and nothing happens. The app go back to the template selection ... no camera, no error message ....
Any help?

**Comment by fttx** [comment]
You're right it may be the cause of the issue.

From the plugin source code I see that it launches the native/stock camera: https://github.com/apache/cordova-plugin-camera/blob/84166f63554903564c9791541ce6f168930a9a61/src/android/CameraLauncher.java#L312

perhaps lineageos includes a camera with a different package name and it is not able to launch it

**Comment by gitschwarz** [comment]
I think the problem is the packetmanager:
"PackageManager mPm = this.cordova.getActivity().getPackageManager();"

Thank you for your time and support.

**Comment by gitschwarz** [comment]
I browsed many site about cordova https://github.com/apache/cordova-plugin-camera/issues?q=camera  and the camera-plugin. It seems that camera plugin doesn't work every time and it is not stable everytime ... 
One Solution :-) :
"I change the plugin. Now I use https://github.com/apache/cordova-plugin-media-capture."

**Comment by gitschwarz** [comment]
Sorry no - not fast ...perhaps in 2 months or so ...
I'm familiar with linux and bash and so  ...

**Comment by fttx** [comment]
Sorry, but where you able to run it using the other plugin? If yes how did you convert the output to base64?

Another user reported a similar issue on a Motorola G5 Plus, is it the same smartphone as yours?

Thank you

**Comment by gitschwarz** [comment]
Thank you for the new versions.
Image Component is now working with lineageos (90%). Only the "ok" -Button (for sending the picture to the server ) is not visible  ....
But this is not a big problem.

**Comment by fttx** [comment]
What is the send button you're referring to? Can you please send a screenshot?

Thanks
