### ISSUE TITLE
"Discard adjacent" option breaks scanning

### ISSUE THREAD

**Issue by eballetbaz** [fttx/barcode-to-pc-app#310]
Tested on IOS and Android:
When option "Discard adjacent" is enabled, then nothing happens after scanning.
If "manual scanning" doesn't work
To reproduce:
- Enable "Discard adjacent" option
- Start a NEW scanning session
- Scan a code or manually enter a code
- Nothing happens

**Comment by fttx** [comment]
Thanks for reporting the issue
