### ISSUE TITLE
Connection problem - diagnosis

### ISSUE THREAD

**Issue by CyrosX** [fttx/barcode-to-pc-app#33]
Hello there,
I've found your very useful app / server combination for barcodes.
But there's one problem:
I can't connect my iPhone to the server on Windows 10 64bit. 
How can I find out, whats the problem?

**Comment by fttx** [comment]
Update the server to the latest version, if it still doesn't work you must enter the server IP manually my tapping the + icon in the "Select server" page. (See here: [Find your PC's IP address](https://support.microsoft.com/en-us/help/15291/windows-find-pc-ip-address)).

**Comment by CyrosX** [comment]
I did that but it didn't work either.
Could the problem be: the iPhone has on an other VLAN and subnet than the pc. (but normally the wifi devices can access this IP area)?

**Comment by fttx** [comment]
As far as i know the server announces the service only in its subnet, this means that the app won't find the server automatically.
Even if you enter the IP address manually it won't connect either because the communication between two different VLAN is forbidden.
