### ISSUE TITLE
Feature-Request: optional always start in Continuous Mode

### ISSUE THREAD

**Issue by JeffZwolle** [fttx/barcode-to-pc-app#63]
After pressing the camera-icon a screen appears where you have to select Single Scan of Continue mode.
Can it be made possible to always start with continuous scanning?
Maybe an extra option in Settings?

**Comment by fttx** [comment]
It will have it in the next version.

Fix: https://github.com/fttx/barcode-to-pc-app/commit/b2ec0c26e95075fbf221cf14e8123a1d990ab0b1

![screenshot_20171112-135520](https://user-images.githubusercontent.com/5663423/32699164-68151484-c7b1-11e7-812c-d238c13beed8.png)
![screenshot_20171112-135528](https://user-images.githubusercontent.com/5663423/32699165-68c41970-c7b1-11e7-927e-531b4cb31ecd.png)
