### ISSUE TITLE
Add a pop-up that notifies the user when the server changes IP address

### ISSUE THREAD

**Issue by fttx** [fttx/barcode-to-pc-app#66]
From the pop-up the user should be able to navigate to Select server page.

Steps to detect the address change:
1. Check if everConnected is false
2. Start scanning for services
3. Compare the defaultServer name against the discovery results

**Comment by bakertaylor28** [comment]
This is better dealt with  by assigning the server a dedicated IP on the LAN, which is something that should be done any time your running a server of any kind on a LAN, for security reasons anyways.

**Comment by fttx** [comment]
Yes, but the average user doesn't even know what an IP address is, and when his computer changes address the app stops working and he doesn't know what to do, that is why i want to add the pop-up
