### ISSUE TITLE
Add setting to limit scanned formats

### ISSUE THREAD

**Issue by st-sloth** [fttx/barcode-to-pc-app#76]
Currently, it seems that `phonegap-plugin-barcodescanner` is trying to scan every "supported" format from the image. In some cases, however, it leads to inability to read the code, while [when run with specific format, the scanner can read the code](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/489#issuecomment-315500405).
Maybe it makes sense to allow the user to limit formats to try to read, like in [Barcode Scanners from Cognex](https://play.google.com/store/apps/details?id=com.manateeworks.barcodescanners)?

**Comment by fttx** [comment]
Yes, it makes sense, i'll add it

**Comment by st-sloth** [comment]
Thank you!

**Comment by niccoX** [comment]
It's been one year since this request was advised. Any reason it's been one year?

**Comment by fttx** [comment]
I've been working on other features, anyway v3.0.0 is almost completed: https://github.com/fttx/barcode-to-pc-app/milestones
