### ISSUE TITLE
Accent chars are not transfered to the computer

### ISSUE THREAD

**Issue by lionelweber** [fttx/barcode-to-pc-app#86]
I'm very please with your application and thank you very much having created this as open-source. I realized that if there are characters like à or é or è, their appear correctly on my smatphone, correctly on the server on the PC, but incorrectly in the applications. For example, I open notepadd++ on win, then type a manual scann with a custom text with accent on my smartphone, then when I press add, the text that appears in notepadd++ on my PC don't contain the accent chars. The same on firefox or other applications.

**Comment by fttx** [comment]
Hi,

thanks for the feedback, i think that it's related to: https://github.com/fttx/barcode-to-pc-server/issues/30

**Comment by lionelweber** [comment]
okay, that means it is still unsolved right? My feedback was just a duplicate, correct? Please indicate me more if there was a fix already developed.
Thanks

**Comment by fttx** [comment]
It's a problem with the [https://github.com/octalmage/robotjs/](robotjs library) it seems that the author fixed it, but he hasn't released a new version yet: https://github.com/octalmage/robotjs/releases
If he'll release it before i'll publish the next update the fix will be included
