### ISSUE TITLE
barcode for italian pharmacy 

### ISSUE THREAD

**Issue by Pietro-Colombo** [fttx/barcode-to-pc-app#91]
Hi in italy we have this code for pharmacy 
http://www.acnet.it/2017/01/18/bollino-farmaceutico-come-configurare-il-lettore-di-codice-a-barre/

but with this app not working.
you have in the pipeline to develop this feature?

tanks in advance

**Comment by fttx** [comment]
Hi,

related to: https://github.com/fttx/barcode-to-pc-app/issues/64
and https://github.com/fttx/barcode-to-pc-app/issues/76

it'll be fixed with the next update

**Comment by pietrocolombo** [comment]
Thanks for the reply.
more or less how long will the update be released?

**Comment by fttx** [comment]
I don't know, maybe a couple of months, i work on it in my spare time
